const DIRTY: &str = "dirty";
const CLEAN_PREPUBLICATION: &str = "clean-prepublication";
const FUTURE_TRANSITION: &str = "future-transition";
const CASES: [&str; 3] = [DIRTY, CLEAN_PREPUBLICATION, FUTURE_TRANSITION];
const EXPECTED_RELEASE_CANDIDATE_ARTIFACTS: [&str; 21] = [
    "fixtures/c2-bodyless-audio-reachability.json",
    "fixtures/c2-health-profile-account.json",
    "fixtures/c2-mobile-handoff.json",
    "fixtures/c4-content-validation.json",
    "fixtures/c4-duplicate.json",
    "fixtures/c4-normal.json",
    "fixtures/c4-permission.json",
    "fixtures/manifest-provenance.json",
    "fixtures/message.created.json",
    "fixtures/mobile-sync-handoff.json",
    "fixtures/realtime-lifecycle.json",
    "fixtures/selected-surface-mapping.json",
    "fixtures/unknown-event-recovery.json",
    "fixtures/version-negotiation.json",
    "manifest.json",
    "openapi.json",
    "realtime/client-frame.schema.json",
    "realtime/message.created.schema.json",
    "realtime/protocol.json",
    "realtime/server-frame.schema.json",
    "realtime/topic.created.schema.json",
];
const EXPECTED_RELEASE_CANDIDATE_ONLY_ARTIFACTS: [&str; 5] = [
    "fixtures/c2-bodyless-audio-reachability.json",
    "fixtures/c2-health-profile-account.json",
    "fixtures/c2-mobile-handoff.json",
    "fixtures/selected-surface-mapping.json",
    "realtime/topic.created.schema.json",
];
const EXPECTED_REST_OPERATIONS: [(&str, &str, &str); 42] = [
    ("H1", "get", "/health/live"),
    ("H2", "get", "/health/ready"),
    ("A1", "post", "/api/v1/auth/oauth/{provider}/authorize"),
    ("A2", "post", "/api/v1/auth/oauth/{provider}/exchange"),
    ("A3", "post", "/api/v1/auth/refresh"),
    ("A4", "post", "/api/v1/auth/logout"),
    ("U1", "get", "/api/v1/me"),
    ("U2", "patch", "/api/v1/me"),
    ("U3", "delete", "/api/v1/me"),
    ("G1", "post", "/api/v1/groups"),
    ("G2", "get", "/api/v1/groups"),
    ("G3", "get", "/api/v1/groups/{group_id}"),
    ("G4", "get", "/api/v1/groups/{group_id}/members"),
    ("G5", "patch", "/api/v1/groups/{group_id}"),
    ("G6", "delete", "/api/v1/groups/{group_id}"),
    (
        "G7",
        "delete",
        "/api/v1/groups/{group_id}/members/{user_id}",
    ),
    ("G8", "patch", "/api/v1/groups/{group_id}/members/{user_id}"),
    ("I1", "post", "/api/v1/groups/{group_id}/invites"),
    ("I2", "post", "/api/v1/invites/{code}/join"),
    ("T1", "post", "/api/v1/groups/{group_id}/topics"),
    ("T2", "get", "/api/v1/groups/{group_id}/topics/dates"),
    ("T3", "get", "/api/v1/groups/{group_id}/topics"),
    ("T4", "get", "/api/v1/groups/{group_id}/topics/{topic_id}"),
    ("T5", "patch", "/api/v1/groups/{group_id}/topics/{topic_id}"),
    (
        "T6",
        "put",
        "/api/v1/groups/{group_id}/topics/{topic_id}/tags",
    ),
    (
        "T7",
        "get",
        "/api/v1/groups/{group_id}/topics/{topic_id}/tags",
    ),
    ("MD1", "post", "/api/v1/media/uploads"),
    ("MD2", "post", "/api/v1/media/uploads/{upload_id}/finalize"),
    ("MD3", "get", "/api/v1/topics/{topic_id}/media"),
    ("C1", "get", "/api/v1/groups/{group_id}/chatrooms"),
    ("C2", "get", "/api/v1/chatrooms/{chatroom_id}/messages"),
    ("C3", "post", "/api/v1/chatrooms/{chatroom_id}/read"),
    ("C4", "post", "/api/v1/chatrooms/{chatroom_id}/messages"),
    ("MD4", "get", "/api/v1/media/{media_id}/url"),
    ("MD5", "get", "/api/v1/media/{media_id}/download"),
    (
        "S1",
        "get",
        "/api/v1/conversations/{conversation_id}/events",
    ),
    ("R1", "post", "/api/v1/realtime/tickets"),
    ("P2", "post", "/api/v1/push/installations"),
    ("P3", "put", "/api/v1/push/installations/{installation_id}"),
    (
        "P4",
        "delete",
        "/api/v1/push/installations/{installation_id}",
    ),
    ("N1", "get", "/api/v1/notifications"),
    ("N2", "post", "/api/v1/notifications/{notification_id}/read"),
];
const EXPECTED_REALTIME_EVENTS: [(&str, u64); 2] = [("message.created", 1), ("topic.created", 1)];
const REST_MAPPING_FIELDS: [&str; 7] = [
    "feature_behavior_test",
    "fixture",
    "handler",
    "handler_route_probe",
    "method",
    "operation_id",
    "path",
];
const REALTIME_MAPPING_FIELDS: [&str; 7] = [
    "event_type",
    "feature_behavior_test",
    "fixture",
    "handler",
    "handler_route_probe",
    "schema",
    "version",
];
const ROUTE_PROBE: &str = "tests/production_composition/composition.rs::api_root_matches_the_complete_frozen_selected_method_path_inventory";
const EXPECTED_REST_MAPPING: [RestMappingOracle; 42] = [
    RestMappingOracle::new(
        "H1",
        "get",
        "/health/live",
        "src/transport/http/health/mod.rs::live",
        "tests/platform.rs::liveness_is_unconditional_and_has_server_request_id",
        "contracts/fixtures/c2-health-profile-account.json",
    ),
    RestMappingOracle::new(
        "H2",
        "get",
        "/health/ready",
        "src/transport/http/health/mod.rs::ready",
        "tests/platform.rs::readiness_requires_postgres_but_only_degrades_optional_services",
        "contracts/fixtures/c2-health-profile-account.json",
    ),
    RestMappingOracle::new(
        "A1",
        "post",
        "/api/v1/auth/oauth/{provider}/authorize",
        "src/transport/http/auth/api.rs::authorize",
        "tests/auth/oauth.rs::authorize_http_separates_shape_semantics_and_stable_rate_limit",
        "contracts/contributions/task-5/fixtures/mobile-auth-handoff.json",
    ),
    RestMappingOracle::new(
        "A2",
        "post",
        "/api/v1/auth/oauth/{provider}/exchange",
        "src/transport/http/auth/api.rs::exchange",
        "tests/auth/oauth.rs::auth_http_happy_path_returns_exact_mobile_token_pairs_and_stores_only_digest",
        "contracts/contributions/task-5/fixtures/mobile-auth-handoff.json",
    ),
    RestMappingOracle::new(
        "A3",
        "post",
        "/api/v1/auth/refresh",
        "src/transport/http/auth/api.rs::refresh",
        "tests/auth/session.rs::concurrent_refresh_allows_one_child_then_reuse_revokes_the_family",
        "contracts/contributions/task-5/fixtures/mobile-auth-handoff.json",
    ),
    RestMappingOracle::new(
        "A4",
        "post",
        "/api/v1/auth/logout",
        "src/transport/http/auth/api.rs::logout",
        "tests/auth/session.rs::logout_revokes_only_refresh_authority_and_access_remains_valid_to_expiry",
        "contracts/contributions/task-5/fixtures/mobile-auth-handoff.json",
    ),
    RestMappingOracle::new(
        "U1",
        "get",
        "/api/v1/me",
        "src/transport/http/users/mod.rs::get_me",
        "tests/profile.rs::get_and_patch_me_use_the_shared_production_bearer_extractor",
        "contracts/fixtures/c2-health-profile-account.json",
    ),
    RestMappingOracle::new(
        "U2",
        "patch",
        "/api/v1/me",
        "src/transport/http/users/mod.rs::patch_me",
        "tests/profile.rs::get_and_patch_me_use_the_shared_production_bearer_extractor",
        "contracts/fixtures/c2-health-profile-account.json",
    ),
    RestMappingOracle::new(
        "U3",
        "delete",
        "/api/v1/me",
        "src/transport/http/account_deletion/mod.rs::delete_account",
        "tests/account_deletion/http.rs::delete_me_commits_one_empty_204_then_revokes_account_access_and_anonymizes_retained_content",
        "contracts/fixtures/c2-health-profile-account.json",
    ),
    RestMappingOracle::new(
        "G1",
        "post",
        "/api/v1/groups",
        "src/transport/http/groups/mod.rs::create_group",
        "tests/groups/http.rs::group_http_crud_paginates_and_enforces_membership_without_disclosure",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "G2",
        "get",
        "/api/v1/groups",
        "src/transport/http/groups/mod.rs::list_groups",
        "tests/groups/http.rs::group_http_crud_paginates_and_enforces_membership_without_disclosure",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "G3",
        "get",
        "/api/v1/groups/{group_id}",
        "src/transport/http/groups/mod.rs::get_group",
        "tests/groups/http.rs::group_http_crud_paginates_and_enforces_membership_without_disclosure",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "G4",
        "get",
        "/api/v1/groups/{group_id}/members",
        "src/transport/http/groups/mod.rs::list_members",
        "tests/groups/http.rs::group_http_crud_paginates_and_enforces_membership_without_disclosure",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "G5",
        "patch",
        "/api/v1/groups/{group_id}",
        "src/transport/http/groups/mod.rs::rename_group",
        "tests/groups/http.rs::group_http_crud_paginates_and_enforces_membership_without_disclosure",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "G6",
        "delete",
        "/api/v1/groups/{group_id}",
        "src/transport/http/groups/mod.rs::delete_group",
        "tests/groups/http.rs::role_invite_join_removal_and_delete_routes_preserve_authority",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "G7",
        "delete",
        "/api/v1/groups/{group_id}/members/{user_id}",
        "src/transport/http/groups/mod.rs::remove_member",
        "tests/groups/http.rs::role_invite_join_removal_and_delete_routes_preserve_authority",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "G8",
        "patch",
        "/api/v1/groups/{group_id}/members/{user_id}",
        "src/transport/http/groups/mod.rs::set_member_role",
        "tests/groups/http.rs::role_invite_join_removal_and_delete_routes_preserve_authority",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "I1",
        "post",
        "/api/v1/groups/{group_id}/invites",
        "src/transport/http/groups/mod.rs::create_invite",
        "tests/groups/http.rs::role_invite_join_removal_and_delete_routes_preserve_authority",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "I2",
        "post",
        "/api/v1/invites/{code}/join",
        "src/transport/http/groups/mod.rs::redeem_invite",
        "tests/groups/http.rs::role_invite_join_removal_and_delete_routes_preserve_authority",
        "contracts/contributions/task-6/fixtures/group-invite-flow.json",
    ),
    RestMappingOracle::new(
        "T1",
        "post",
        "/api/v1/groups/{group_id}/topics",
        "src/transport/http/topics/mod.rs::create_topic",
        "tests/topics/http.rs::t1_through_t7_http_use_the_locked_authenticated_mobile_shapes",
        "contracts/contributions/task-7/fixtures/topic-flow.json",
    ),
    RestMappingOracle::new(
        "T2",
        "get",
        "/api/v1/groups/{group_id}/topics/dates",
        "src/transport/http/topics/mod.rs::list_topic_dates",
        "tests/topics/http.rs::t1_through_t7_http_use_the_locked_authenticated_mobile_shapes",
        "contracts/contributions/task-7/fixtures/topic-flow.json",
    ),
    RestMappingOracle::new(
        "T3",
        "get",
        "/api/v1/groups/{group_id}/topics",
        "src/transport/http/topics/mod.rs::list_topics",
        "tests/topics/http.rs::t1_through_t7_http_use_the_locked_authenticated_mobile_shapes",
        "contracts/contributions/task-7/fixtures/topic-flow.json",
    ),
    RestMappingOracle::new(
        "T4",
        "get",
        "/api/v1/groups/{group_id}/topics/{topic_id}",
        "src/transport/http/topics/mod.rs::get_topic",
        "tests/topics/http.rs::t1_through_t7_http_use_the_locked_authenticated_mobile_shapes",
        "contracts/contributions/task-7/fixtures/topic-flow.json",
    ),
    RestMappingOracle::new(
        "T5",
        "patch",
        "/api/v1/groups/{group_id}/topics/{topic_id}",
        "src/transport/http/topics/mod.rs::patch_topic",
        "tests/topics/http.rs::t1_through_t7_http_use_the_locked_authenticated_mobile_shapes",
        "contracts/contributions/task-7/fixtures/topic-flow.json",
    ),
    RestMappingOracle::new(
        "T6",
        "put",
        "/api/v1/groups/{group_id}/topics/{topic_id}/tags",
        "src/transport/http/topics/mod.rs::replace_tags",
        "tests/topics/http.rs::t1_through_t7_http_use_the_locked_authenticated_mobile_shapes",
        "contracts/contributions/task-7/fixtures/topic-flow.json",
    ),
    RestMappingOracle::new(
        "T7",
        "get",
        "/api/v1/groups/{group_id}/topics/{topic_id}/tags",
        "src/transport/http/topics/mod.rs::list_tags",
        "tests/topics/http.rs::t1_through_t7_http_use_the_locked_authenticated_mobile_shapes",
        "contracts/contributions/task-7/fixtures/topic-flow.json",
    ),
    RestMappingOracle::new(
        "MD1",
        "post",
        "/api/v1/media/uploads",
        "src/transport/http/media/mod.rs::create_upload_intent",
        "tests/media/upload_finalize_http.rs::md1_returns_a_server_minted_intent_and_constrained_put",
        "contracts/contributions/task-8/fixtures/media-flow.json",
    ),
    RestMappingOracle::new(
        "MD2",
        "post",
        "/api/v1/media/uploads/{upload_id}/finalize",
        "src/transport/http/media/mod.rs::finalize_upload",
        "tests/media/upload_finalize_http.rs::md2_chat_finalize_returns_the_confirmed_unbound_capability",
        "contracts/contributions/task-8/fixtures/media-flow.json",
    ),
    RestMappingOracle::new(
        "MD3",
        "get",
        "/api/v1/topics/{topic_id}/media",
        "src/transport/http/topics/mod.rs::list_media",
        "tests/media/md3_http.rs::md3_returns_stable_paginated_canonical_topic_media",
        "contracts/contributions/task-8/fixtures/media-flow.json",
    ),
    RestMappingOracle::new(
        "C1",
        "get",
        "/api/v1/groups/{group_id}/chatrooms",
        "src/transport/http/chatrooms/mod.rs::list_chatrooms",
        "tests/chatrooms/http.rs::c1_c2_and_c3_http_use_exact_authenticated_mobile_shapes",
        "contracts/contributions/task-6b/fixtures/chatroom-history-read.json",
    ),
    RestMappingOracle::new(
        "C2",
        "get",
        "/api/v1/chatrooms/{chatroom_id}/messages",
        "src/transport/http/chatrooms/mod.rs::message_history",
        "tests/chatrooms/http.rs::c1_c2_and_c3_http_use_exact_authenticated_mobile_shapes",
        "contracts/contributions/task-6b/fixtures/chatroom-history-read.json",
    ),
    RestMappingOracle::new(
        "C3",
        "post",
        "/api/v1/chatrooms/{chatroom_id}/read",
        "src/transport/http/chatrooms/mod.rs::mark_read",
        "tests/chatrooms/http.rs::c1_c2_and_c3_http_use_exact_authenticated_mobile_shapes",
        "contracts/contributions/task-6b/fixtures/chatroom-history-read.json",
    ),
    RestMappingOracle::new(
        "C4",
        "post",
        "/api/v1/chatrooms/{chatroom_id}/messages",
        "src/transport/http/messaging/mod.rs::create_message",
        "tests/messaging/http.rs::c4_preserves_content_idempotency_and_exact_text",
        "contracts/fixtures/c4-normal.json",
    ),
    RestMappingOracle::new(
        "MD4",
        "get",
        "/api/v1/media/{media_id}/url",
        "src/transport/http/media/mod.rs::view_url",
        "tests/media/access_http.rs::md4_returns_only_public_metadata_and_the_short_reissued_url",
        "contracts/contributions/task-8/fixtures/media-flow.json",
    ),
    RestMappingOracle::new(
        "MD5",
        "get",
        "/api/v1/media/{media_id}/download",
        "src/transport/http/media/mod.rs::download",
        "tests/media/access_http.rs::md5_returns_an_empty_307_redirect_to_the_authorized_download_url",
        "contracts/contributions/task-8/fixtures/media-flow.json",
    ),
    RestMappingOracle::new(
        "S1",
        "get",
        "/api/v1/conversations/{conversation_id}/events",
        "src/transport/http/messaging/mod.rs::events",
        "tests/messaging/delta.rs::s1_pages_strictly_forward_across_commits_and_an_unknown_marker",
        "contracts/fixtures/mobile-sync-handoff.json",
    ),
    RestMappingOracle::new(
        "R1",
        "post",
        "/api/v1/realtime/tickets",
        "src/transport/http/realtime/mod.rs::issue_ticket",
        "tests/realtime/ticket.rs::ticket_is_capped_by_access_expiry_and_consumed_exactly_once",
        "contracts/fixtures/realtime-lifecycle.json",
    ),
    RestMappingOracle::new(
        "P2",
        "post",
        "/api/v1/push/installations",
        "src/transport/http/push/mod.rs::upsert_installation",
        "tests/notifications/http.rs::p2_uses_create_then_canonical_upsert_status_and_never_returns_private_fields",
        "contracts/contributions/task-9/fixtures/notifications-push-flow.json",
    ),
    RestMappingOracle::new(
        "P3",
        "put",
        "/api/v1/push/installations/{installation_id}",
        "src/transport/http/push/mod.rs::update_installation",
        "tests/notifications/http.rs::p3_and_p4_are_current_owner_scoped_and_keep_the_public_response_shape",
        "contracts/contributions/task-9/fixtures/notifications-push-flow.json",
    ),
    RestMappingOracle::new(
        "P4",
        "delete",
        "/api/v1/push/installations/{installation_id}",
        "src/transport/http/push/mod.rs::delete_installation",
        "tests/notifications/http.rs::p3_and_p4_are_current_owner_scoped_and_keep_the_public_response_shape",
        "contracts/contributions/task-9/fixtures/notifications-push-flow.json",
    ),
    RestMappingOracle::new(
        "N1",
        "get",
        "/api/v1/notifications",
        "src/transport/http/notifications/mod.rs::list_notifications",
        "tests/notifications/http.rs::n1_returns_the_owner_scoped_structured_page_without_private_state",
        "contracts/contributions/task-9/fixtures/notifications-push-flow.json",
    ),
    RestMappingOracle::new(
        "N2",
        "post",
        "/api/v1/notifications/{notification_id}/read",
        "src/transport/http/notifications/mod.rs::mark_notification_read",
        "tests/notifications/http.rs::n2_is_idempotent_and_missing_or_foreign_ids_share_one_safe_not_found",
        "contracts/contributions/task-9/fixtures/notifications-push-flow.json",
    ),
];
